export  const atividade = [
    { value: '1', label: 'REST/PIZZ/CHURRASC/BARES/CERV/CHOPERIAS' },
    { value: '3', label: 'LANCHONETES/PAMONHARIAS/SORVETERIAS' },
    { value: '4', label: 'COZINHAS INDUSTRIAIS' },
    { value: '5', label: 'INDUSTRIA AUTOMOBILISTICA/METALURGICA' },
    { value: '6', label: 'INDUSTRIAS DE BEBIDAS' },
    { value: '7', label: 'INDUSTRIAS DE CONFECCAO' },
    { value: '8', label: 'INDUSTRIAS EM GERAL' },
    { value: '9', label: 'INDUSTRIAS ALIMENTICIAS' },
    { value: '10', label: 'INDUSTRIAS FARMACEUTICAS' },
    { value: '11', label: 'CONCESSIONARIAS / OFICINAS' },
    { value: '12', label: 'ESCRITORIO DE CONTABILIDADE' },
    { value: '13', label: 'ESCRITORIO DE ADVOCACIA/ADVOGADOS' },
    { value: '14', label: 'SINDICATOS' },
    { value: '15', label: 'CLINICAS ODONTOLOGICAS' },
    { value: '16', label: 'HOTEIS/FLATS' },
    { value: '17', label: 'MOTEIS' },
    { value: '18', label: 'ATACADISTAS/DISTRIBUIDORES' },
    { value: '19', label: 'VAREJOS' },
    { value: '20', label: 'COOPERATIVAS/ASSOCIACOES/FAZENDAS' },
    { value: '21', label: 'IGREJAS/TEMPLOS' },
    { value: '22', label: 'EMPRESAS DE COMUNICACAO' },
    { value: '23', label: 'SEGURADORA' },
    { value: '24', label: 'AGENCIA/PUBLICIDADE/PROPAGANDA/VIAGEM' },
    { value: '25', label: 'FRUTARIA/VERDURAO' },
    { value: '26', label: 'POSTO DE GASOLINA' },
    { value: '27', label: 'CONSTRUT/ENGENHARIA/ARQUITET/IMOBILIARIA' },
    { value: '28', label: 'ESCOLAS/BERCARIOS/CRECHE' },
    { value: '29', label: 'FACULDADES/CURSOS' },
    { value: '30', label: 'DOUTORES/CONSULTORIOS' },
    { value: '31', label: 'FARMACIAS/DROGARIAS' },
    { value: '32', label: 'CONSERV/LIMP/VIG/PRESTADOR DE SERVICOS' },
    { value: '33', label: 'PRESTACAO DE SERVICOS' },
    { value: '34', label: 'CLUBES' },
    { value: '35', label: 'CINEMAS/TEATROS' },
    { value: '36', label: 'ORGAOS PUBLICOS' },
    { value: '37', label: 'CLINICA VETERINARIA' },
    { value: '38', label: 'CENTROS ESPORTIVOS' },
    { value: '39', label: 'ACADEMIAS/SAUNAS' },
    { value: '40', label: 'CEMITERIOS/FUNERARIA' },
    { value: '41', label: 'CONFEITARIAS/PANIFICADORAS' },
    { value: '42', label: 'HOSPITAIS' },
    { value: '43', label: 'CLINICAS EM GERAL' },
    { value: '44', label: 'CASA DE SHOWS/BOATES' },
    { value: '45', label: 'CASA DE FESTA/BUFFET' },
    { value: '46', label: 'AEROPORTO' },
    { value: '47', label: 'RODOVIARIA' },
    { value: '48', label: 'DOMESTICO/CONSUMIDOR' },
    { value: '49', label: 'BANCOS/FINANC./CONSORC./SE' },
    { value: '50', label: 'CONDOMINIOS EMPRESARIAIS/RESIDENCIAIS' },
    { value: '51', label: 'EMPRESAS DE TRANSPORTES' },
    { value: '52', label: 'GRANJAS/ABATEDOUROS' },
    { value: '53', label: 'LATICINIOS' },
    { value: '54', label: 'FRIGORIFICOS' },
    { value: '55', label: 'GRAFICAS E EDITORAS' },
    { value: '56', label: 'JOALHEIRA/OTICA' },
    { value: '57', label: 'EMBALADORES/CEASA/FEIRANTES' },
    { value: '58', label: 'CARTORIOS' },
    { value: '59', label: 'LABORATORIO DE ANALISE' },
    { value: '60', label: 'SALAO DE BELEZA' },
    { value: '61', label: 'SHOPPING' },
    { value: '62', label: 'SUPERMERCADOS' },
    { value: '63', label: 'DESATIVADOS' },
    { value: '64', label: 'FORNECEDOR' },
    { value: '65', label: 'EXCLUIDOS' },
    { value: '66', label: 'CONCORRENTE' },
    { value: '67', label: 'FUNCIONARIO' },
    { value: '68', label: 'LUCROS E PERDAS' },
    { value: '69', label: 'LAVANDERIA' },
    { value: '70', label: 'PAPELARIA' },

]