type PracaOption = {
    value: string;
    label: string;
};

export const opstionsPraca: PracaOption[] = [
    { value: '1', label: 'FORNECEDORES' },
    { value: '2', label: 'PRACA SUL' },
    { value: '3', label: 'PRACA MARISTA' },
    { value: '4', label: 'PRACA OESTE' },
    { value: '5', label: 'PRACA COIMBRA' },
    { value: '6', label: 'COLABORADORES R3' },
    { value: '7', label: 'PRACA JARDIM AMERICA' },
    { value: '8', label: 'PRACA NOVA SUICA' },
    { value: '9', label: 'PRACA ST PEDRO LUDOVICO' },
    { value: '10', label: 'PRACA JARDIM GOIAS' },
    { value: '11', label: 'PRACA ALTO DA GLORIA' },
    { value: '12', label: 'PRACA VILA REDENCAO' },
    { value: '13', label: 'PRACA PQ DAS LARANJEIRAS' },
    { value: '14', label: 'PRACA ST LESTE UNIVERSITA' },
    { value: '15', label: 'PRACA JARDIM NOVO MUNDO' },
    { value: '16', label: 'PRACA VILA BANDEIRANTES' },
    { value: '17', label: 'PRACA ST LESTE VILA NOVA' },
    { value: '18', label: 'PRACA ST SANTA GENOVEVA' },
    { value: '19', label: 'PRACA CEASA' },
    { value: '20', label: 'PRACA GOIANIA II' },
    { value: '21', label: 'PRACA ST URIAS MAGALHAES' },
    { value: '22', label: 'PRACA ST SUDOESTE' },
    { value: '23', label: 'PRACA JD ATLANTICO' },
    { value: '24', label: 'PRACA AP DE GYN - LESTE' },
    { value: '25', label: 'PRACA AP DE GYN - OESTE' },
    { value: '26', label: 'PRACA SENADOR CANEDO' },
    { value: '27', label: 'PRACA NEROPOLIS' },
    { value: '28', label: 'PRACA RIO VERDE/JATAI ' },
    { value: '29', label: 'PRACA ANAPOLIS E ENTORNO' },
    { value: '30', label: 'PRACA INTERIORES GO V.I.' },
    { value: '31', label: 'ENTREGA FORA DO ESTADO' },
    { value: '32', label: 'TESTE SIMPLES NACIONAL' },
    { value: '33', label: 'PRACA POLO INDUSTRIAL' },
    { value: '34', label: 'PRACA POLO EMPRESARIAL' },
    { value: '35', label: 'PRAÇA TESTE MAX' },
    { value: '36', label: 'DISTRITO FEDERAL' },
    { value: '37', label: 'BAHIA' },
    { value: '38', label: 'TRANSPORTADORA G5' },
    { value: '39', label: 'REGIAO NORTE' },
    { value: '40', label: 'SUDOESTE GOIANO' },
    { value: '41', label: 'TRANSP TRANS SILVA' },
    { value: '42', label: 'FORA DE GOIÁS' },
    { value: '43', label: 'REGIAO CENTRO OESTE' },
    { value: '44', label: 'REGIAO NOROESTE' },
    { value: '45', label: 'REGIAO SUL' },
    { value: '46', label: 'REGIAO OESTE' },
    { value: '47', label: 'REGIAO LESTE/APARECIDA' },
    { value: '48', label: 'REGIAO SUDOESTE' },
    { value: '49', label: 'REGIAO METROPOLITANA' },
    { value: '50', label: 'TRANSP ATUAL CARGAS' },
    { value: '51', label: 'MINAS GERAIS' },
    { value: '52', label: 'MATO GROSSO' },
    { value: '53', label: 'PARA' },
    { value: '54', label: 'SUL E SUDESTE GOIANO' },
    { value: '55', label: 'TOCANTINS' },
    { value: '56', label: 'MATO GROSSO DO SUL' },
    { value: '57', label: 'ECOMMERCE B2C' },
    { value: '58', label: 'ECOMMERCE B2B' },
    { value: '59', label: 'AMAZONAS' },
    { value: '60', label: 'PIAUI' },
    { value: '61', label: 'RIO GRAN. SUL' },
    { value: '62', label: 'PARANA' },
    { value: '63', label: 'RIO DE JANEIRO' },
    { value: '64', label: 'ESPIRITO SANTO' },
    { value: '65', label: 'SAO PAULO' },
    { value: '66', label: 'ALAGOAS' },
    { value: '67', label: 'PARAIBA' },
    { value: '68', label: 'RIO GRA. NORTE' },
    { value: '69', label: 'CEARA' },
    { value: '70', label: 'MARANHAO' },
    { value: '71', label: 'AMAPA' },
    { value: '72', label: 'RONDONIA' },
    { value: '73', label: 'ACRE' },
    { value: '74', label: 'RIO GRAN. SUL' },
    { value: '75', label: 'GRUPO NATUREZA' },
    { value: '76', label: 'GRUPO SAO ROQUE' },

]; 